apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: so4n5o4i9-dotnet-basic
  janus-idp.io/tekton: so4n5o4i9-dotnet-basic
  backstage.io/kubernetes-id: so4n5o4i9-dotnet-basic
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: so4n5o4i9-dotnet-basic
resources:
- deployment.yaml
- route.yaml
- service.yaml
